Homework9: Yura Buzinau
Eystei/pymar2024 pull request #10
Opened 2024-05-29 19:03 UTC by Eystei

Homework9: Yura Buzinau

2024-06-01 20:09 UTC, Stml89 requested changes, later dismissed

2024-06-01 20:09 UTC, Stml89 commented on home_work/hw_9/candles/candles.py
> +    print(burn_candles(5, 2))
you do not need to print anything here, but if you want to log something use logger module 
https://docs.python.org/3/library/logging.html

2024-06-01 20:09 UTC, Stml89 commented on home_work/hw_9/counting_letters/counting_letters.py
> +    for string in ALL_STRINGS:
you have an overcomplicated solution a bit, to use simple `assert`. 

simple is better than complex:
```
assert("cccbba") == "c3b2a", <error message>
...
assert("aaabbdefffff") == "", <error message>
```

2024-06-01 20:09 UTC, Stml89 commented on home_work/hw_9/strings_with_symb/strings_with_symb.py
the same problem as in the previous module

2024-06-01 20:09 UTC, Stml89 commented on home_work/test.py
have you shared this solution with someone from the group? I saw exactly the same code...

2024-06-03 04:54 UTC, Eystei commented on home_work/test.py
Nope, I haven't shared this solution with anyone from the group. I solved it myself first, then asked ChatGPT to review the code and optimize it if necessary.

2024-06-06 20:05 UTC, Stml89 commented on home_work/test.py
aha, so some of the students are using chatGPT. Thx

2024-06-06 20:13 UTC, Stml89 approved these changes
In general it is OK, please fix small comments and you can merge it

2024-06-06 20:13 UTC, Stml89 commented on home_work/test.py
this module is a bit different from others:
1) you do not use type hints
2) you do not use asserts
3) you start using the following construction(https://www.freecodecamp.org/news/if-name-main-python-example/): 
`
if __name__ = ....
`

2024-06-07 12:18 UTC, Eystei commented on home_work/test.py
It was for experiments, I forgot to delete it. Deleted now

2024-06-07 12:18 UTC, merged